export default {
  typography: {
    fontFamily: '"IBM Plex Sans", sans-serif',
    fontSize: '16px',
    lineHeight: 1.45,
    fontWeight: '400',
    h1: {
      fontSize: '3.052rem',
      lineHeight: 1.15,
      fontWeight: 700,
      fontFamily: '"IBM Plex Sans", sans-serif',
    },
    h2: {
      fontSize: '2.441rem',
      lineHeight: 1.15,
      fontWeight: 700,
      fontFamily: '"IBM Plex Sans", sans-serif',
    },
    h3: {
      fontSize: '1.953rem',
      lineHeight: 1.15,
      fontWeight: 700,
      fontFamily: '"IBM Plex Sans", sans-serif',
    },
    h4: {
      fontSize: '1.563rem',
      lineHeight: 1.15,
      fontWeight: 700,
      fontFamily: '"IBM Plex Sans", sans-serif',
    },
    h5: {
      fontSize: '1.25rem',
      lineHeight: 1.15,
      fontWeight: 700,
      fontFamily: '"IBM Plex Sans", sans-serif',
    },
    h6: {
      fontSize: '1rem',
      lineHeight: 1.15,
      fontWeight: 700,
      fontFamily: '"IBM Plex Sans", sans-serif',
    },
    body: {
      fontSize: '1rem',
      lineHeight: 1.45,
      fontWeight: 400,
      fontFamily: '"IBM Plex Sans", sans-serif',
    },
    caption: {
      fontSize: '.8rem',
      lineHeight: 1.45,
      fontWeight: 400,
      fontFamily: '"IBM Plex Sans", sans-serif',
    },
  },
  colors: {
    primary: '#21AAE2',
    secondary: '#DB5461',
    dark: '#303334',
    lightDark: '#4E5355',
    light: '#EFF1F3',
    lighter: '#FEFFFE',
    error: '#FF3C38',
    success: '#FFCA1E',
    warning: '#78BE20',
  },
  space: [0, 4, 8, 16, 32, 64, 128, 256],
  breakpoints: {
    xs: 0,
    sm: 576,
    md: 768,
    lg: 992,
    xl: 1200,
  },
};
